# Final datasets preparation and Feature Engineering

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\bedge\Desktop\NHANES\MergedDataR_new.csv")

In [3]:
data.head()

,Unnamed: 0,id,persWt,examWt,psu,strata,gender,age,race,pregnancy_status,...,diastolicBP2,systolicBP3,diastolicBP3,urine_alb_creat,hdl_cholesterol,triglycerides,total_cholesterol,fasting.glucose,hba1c,hscrp
0,4,109266,7825.646112,8154.968193,2,168,2,29,5,2.0,...,55.0,99.0,52.0,15.28,56.0,NaN,195.0,NaN,5.2,0.72
1,5,109267,26379.991724,0.000000,1,156,2,21,2,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9,109271,8481.589837,8658.732873,1,167,1,49,3,NaN,...,68.0,111.0,68.0,7.50,33.0,84.0,147.0,103.0,5.6,28.68
3,11,109273,20171.847767,22163.596850,1,155,1,36,3,NaN,...,66.0,115.0,68.0,4.05,42.0,NaN,164.0,NaN,5.1,0.98
4,12,109274,7227.993241,7801.600218,2,167,1,68,5,NaN,...,69.0,132.0,71.0,10.67,29.0,133.0,105.0,154.0,5.7,1.60

In [4]:
data.shape

(9232, 40)

In [5]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,9232.0,7799.091746,4488.309008,4.000000,3919.250000,7759.500000,11683.250000,15560.000000
id,9232.0,117061.091746,4488.309008,109266.000000,113181.250000,117021.500000,120945.250000,124822.000000
persWt,9232.0,26045.222372,30129.287779,1876.867755,9222.482331,15775.584026,29598.676751,338363.600192
examWt,9232.0,26045.222382,32251.598510,0.000000,8453.811011,15583.537858,30028.847927,367555.742979
psu,9232.0,1.541919,0.543202,1.000000,1.000000,2.000000,2.000000,3.000000
strata,9232.0,160.227253,6.958216,149.000000,154.000000,160.000000,166.000000,172.000000
gender,9232.0,1.514840,0.499807,1.000000,1.000000,2.000000,2.000000,2.000000
age,9232.0,51.144931,17.686659,20.000000,36.000000,52.000000,65.000000,80.000000
race,9232.0,3.273289,1.194610,1.000000,3.000000,3.000000,4.000000,5.000000
pregnancy_status,1874.0,2.051227,0.376202,1.000000,2.000000,2.000000,2.000000,3.000000
education,9232.0,3.551993,1.214109,1.000000,3.000000,4.000000,4.000000,9.000000
marital_status,9232.0,1.708622,2.755878,1.000000,1.000000,1.000000,2.000000,99.000000
monthly_poverty_level_index,7173.0,2.404654,1.560868,0.000000,1.110000,1.980000,3.660000,5.000000
monthly_poverty_level_category,8383.0,2.478945,1.556309,1.000000,1.000000,3.000000,3.000000,9.000000
health_insurance,9232.0,1.176451,0.508998,1.000000,1.000000,1.000000,1.000000,9.000000
food_security,8543.0,1.691912,1.025609,1.000000,1.000000,1.000000,2.000000,4.000000
bp_question,9232.0,1.623159,0.554667,1.000000,1.000000,2.000000,2.000000,9.000000
bp_medication,3270.0,1.149235,0.356375,1.000000,1.000000,1.000000,1.000000,2.000000
chol_question,9232.0,1.696382,0.778597,1.000000,1.000000,2.000000,2.000000,9.000000
chol_medication,2742.0,1.294675,0.642046,1.000000,1.000000,1.000000,2.000000,9.000000
diabetes_question,9232.0,1.878358,0.440403,1.000000,2.000000,2.000000,2.000000,9.000000
take_insulin,1420.0,1.714085,0.493737,1.000000,1.000000,2.000000,2.000000,9.000000
antidiabetic_pills,2596.0,1.580508,0.592885,1.000000,1.000000,2.000000,2.000000,9.000000
weight,8402.0,83.688396,23.184992,32.600000,67.625000,79.900000,95.800000,254.300000
height,8395.0,166.641251,10.082700,131.100000,159.100000,166.200000,173.900000,199.600000
bmi,8381.0,30.039017,7.565943,14.200000,24.900000,28.800000,33.800000,92.300000
waist_circumference,8055.0,100.987039,17.130987,57.900000,89.000000,99.500000,111.500000,187.500000
systolicBP1,7648.0,125.075052,19.947541,66.000000,111.000000,122.000000,136.000000,225.000000
diastolicBP1,7648.0,75.205936,11.943487,36.000000,67.000000,74.000000,82.000000,151.000000
systolicBP2,7637.0,124.791672,19.746599,69.000000,111.000000,122.000000,136.000000,222.000000
diastolicBP2,7637.0,74.638209,11.897873,31.000000,66.000000,74.000000,82.000000,146.000000
systolicBP3,7619.0,124.691823,19.553302,60.000000,111.000000,122.000000,135.000000,220.000000
diastolicBP3,7619.0,74.325502,11.932551,36.000000,66.000000,74.000000,82.000000,145.000000
urine_alb_creat,8319.0,52.678134,354.847461,0.270000,4.900000,7.670000,15.240000,11676.920000
hdl_cholesterol,7921.0,53.560535,15.977751,5.000000,42.000000,51.000000,62.000000,189.000000
triglycerides,3934.0,109.832740,94.734548,10.000000,60.000000,89.000000,132.750000,2684.000000
total_cholesterol,7921.0,185.579725,41.012095,71.000000,157.000000,182.000000,211.000000,446.000000
fasting.glucose,4004.0,113.571678,38.096333,47.000000,96.000000,103.000000,115.000000,451.000000
hba1c,8081.0,5.862381,1.121543,2.800000,5.300000,5.600000,6.000000,16.200000
hscrp,7864.0,4.211480,8.786133,0.110000,0.860000,1.990000,4.520000,246.860000

# Feature Engineering

In [6]:
# we used National Cholesterol Education Program, Adult Treatment Panel III (NCEP ATP III) criteria
#citation: 'Grundy SM, Becker D. Detection, evaluation, and treatment of high blood cholesterol in adults (Adult Treatment Panel III). Circulation. 2002;106(25):3143â€“421"
# Define a function to apply the criteria and return 1 or 0
#criteria_1: Abdominal_obesity
def abdominal_obesity(row):
    if (row['gender'] == 1 and row['waist_circumference'] > 102) or
        (row['gender'] == 2 and row['waist_circumference'] > 88): #gender 1 is Male and 2 is Female
        return 1
    else:
        return 0
#criteria_2: Triglycerides_high
def triglycerides_high(row):
    if(row['triglycerides'] >=150): 
        return 1
    else:
        return 0
#criteria_3: HDL_low
def HDL_low(row):
    if (row['gender'] == 1 and row['hdl_cholesterol'] < 40) or 
        (row['gender'] == 2 and row['hdl_cholesterol'] < 50): #gender 1 is Male and 2 is Female
        return 1
    else:
        return 0
#Criteria_4: High_BP
def High_BP(row):
    #if (row['systolicBP1'] or row['systolicBP2'] or row['systolicBP3'] >= 130) or (row['diastolicBP1'] or row['diastolicBP2'] or row['diastolicBP3'] >=85):
    if (row['systolicBP1'] >= 130 or row['systolicBP2'] >= 130 or 
        row['systolicBP3'] >= 130) or (row['diastolicBP1'] >= 85 or 
        row['diastolicBP2'] >= 85 or row['diastolicBP3'] >= 85) or row['bp_medication']==1:

        return 1
    else:
        return 0
#Criteria_5:Fasting_Glucose >=100
def abnormal_glucose(row):
    if(row['fasting.glucose'] >=100 or row['antidiabetic_pills']==1 or row['take_insulin'] == 1):
        return 1
    else:
        return 0

# Apply the function to create the new column for each criteria
data['Abdominal_obesity'] = data.apply(abdominal_obesity, axis=1)
data['Triglycerides_high'] = data.apply(triglycerides_high,axis=1)
data['HDL_low'] = data.apply(HDL_low, axis=1)
data['High_BP'] = data.apply(High_BP, axis=1)
data['Abnormal_glucose']= data.apply(abnormal_glucose, axis=1)


#Criteria Definining Metabolic syndrome

def Metabolic_syndrome(row):
    criteria_count = row['Abdominal_obesity'] + row['Triglycerides_high'] + row['HDL_low'] + row['High_BP'] + row['Abnormal_glucose']
    if criteria_count >= 3:
        return 1
    else:
        return 0
    
# Apply function to create new column for the Metabolic syndrome
data['metabolic_syndrome'] = data.apply(Metabolic_syndrome, axis=1)

In [7]:
data.shape

(9232, 46)

In [8]:
data.head()

,Unnamed: 0,id,persWt,examWt,psu,strata,gender,age,race,pregnancy_status,...,total_cholesterol,fasting.glucose,hba1c,hscrp,Abdominal_obesity,Triglycerides_high,HDL_low,High_BP,Abnormal_glucose,metabolic_syndrome
0,4,109266,7825.646112,8154.968193,2,168,2,29,5,2.0,...,195.0,NaN,5.2,0.72,1,0,0,0,0,0
1,5,109267,26379.991724,0.000000,1,156,2,21,2,3.0,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
2,9,109271,8481.589837,8658.732873,1,167,1,49,3,NaN,...,147.0,103.0,5.6,28.68,1,0,1,0,1,1
3,11,109273,20171.847767,22163.596850,1,155,1,36,3,NaN,...,164.0,NaN,5.1,0.98,0,0,0,0,0,0
4,12,109274,7227.993241,7801.600218,2,167,1,68,5,NaN,...,105.0,154.0,5.7,1.60,1,0,1,1,1,1

In [9]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,9232.0,7799.091746,4488.309008,4.000000,3919.250000,7759.500000,11683.250000,15560.000000
id,9232.0,117061.091746,4488.309008,109266.000000,113181.250000,117021.500000,120945.250000,124822.000000
persWt,9232.0,26045.222372,30129.287779,1876.867755,9222.482331,15775.584026,29598.676751,338363.600192
examWt,9232.0,26045.222382,32251.598510,0.000000,8453.811011,15583.537858,30028.847927,367555.742979
psu,9232.0,1.541919,0.543202,1.000000,1.000000,2.000000,2.000000,3.000000
strata,9232.0,160.227253,6.958216,149.000000,154.000000,160.000000,166.000000,172.000000
gender,9232.0,1.514840,0.499807,1.000000,1.000000,2.000000,2.000000,2.000000
age,9232.0,51.144931,17.686659,20.000000,36.000000,52.000000,65.000000,80.000000
race,9232.0,3.273289,1.194610,1.000000,3.000000,3.000000,4.000000,5.000000
pregnancy_status,1874.0,2.051227,0.376202,1.000000,2.000000,2.000000,2.000000,3.000000
education,9232.0,3.551993,1.214109,1.000000,3.000000,4.000000,4.000000,9.000000
marital_status,9232.0,1.708622,2.755878,1.000000,1.000000,1.000000,2.000000,99.000000
monthly_poverty_level_index,7173.0,2.404654,1.560868,0.000000,1.110000,1.980000,3.660000,5.000000
monthly_poverty_level_category,8383.0,2.478945,1.556309,1.000000,1.000000,3.000000,3.000000,9.000000
health_insurance,9232.0,1.176451,0.508998,1.000000,1.000000,1.000000,1.000000,9.000000
food_security,8543.0,1.691912,1.025609,1.000000,1.000000,1.000000,2.000000,4.000000
bp_question,9232.0,1.623159,0.554667,1.000000,1.000000,2.000000,2.000000,9.000000
bp_medication,3270.0,1.149235,0.356375,1.000000,1.000000,1.000000,1.000000,2.000000
chol_question,9232.0,1.696382,0.778597,1.000000,1.000000,2.000000,2.000000,9.000000
chol_medication,2742.0,1.294675,0.642046,1.000000,1.000000,1.000000,2.000000,9.000000
diabetes_question,9232.0,1.878358,0.440403,1.000000,2.000000,2.000000,2.000000,9.000000
take_insulin,1420.0,1.714085,0.493737,1.000000,1.000000,2.000000,2.000000,9.000000
antidiabetic_pills,2596.0,1.580508,0.592885,1.000000,1.000000,2.000000,2.000000,9.000000
weight,8402.0,83.688396,23.184992,32.600000,67.625000,79.900000,95.800000,254.300000
height,8395.0,166.641251,10.082700,131.100000,159.100000,166.200000,173.900000,199.600000
bmi,8381.0,30.039017,7.565943,14.200000,24.900000,28.800000,33.800000,92.300000
waist_circumference,8055.0,100.987039,17.130987,57.900000,89.000000,99.500000,111.500000,187.500000
systolicBP1,7648.0,125.075052,19.947541,66.000000,111.000000,122.000000,136.000000,225.000000
diastolicBP1,7648.0,75.205936,11.943487,36.000000,67.000000,74.000000,82.000000,151.000000
systolicBP2,7637.0,124.791672,19.746599,69.000000,111.000000,122.000000,136.000000,222.000000
diastolicBP2,7637.0,74.638209,11.897873,31.000000,66.000000,74.000000,82.000000,146.000000
systolicBP3,7619.0,124.691823,19.553302,60.000000,111.000000,122.000000,135.000000,220.000000
diastolicBP3,7619.0,74.325502,11.932551,36.000000,66.000000,74.000000,82.000000,145.000000
urine_alb_creat,8319.0,52.678134,354.847461,0.270000,4.900000,7.670000,15.240000,11676.920000
hdl_cholesterol,7921.0,53.560535,15.977751,5.000000,42.000000,51.000000,62.000000,189.000000
triglycerides,3934.0,109.832740,94.734548,10.000000,60.000000,89.000000,132.750000,2684.000000
total_cholesterol,7921.0,185.579725,41.012095,71.000000,157.000000,182.000000,211.000000,446.000000
fasting.glucose,4004.0,113.571678,38.096333,47.000000,96.000000,103.000000,115.000000,451.000000
hba1c,8081.0,5.862381,1.121543,2.800000,5.300000,5.600000,6.000000,16.200000
hscrp,7864.0,4.211480,8.786133,0.110000,0.860000,1.990000,4.520000,246.860000
Abdominal_obesity,9232.0,0.527621,0.499264,0.000000,0.000000,1.000000,1.000000,1.000000
Triglycerides_high,9232.0,0.080156,0.271549,0.000000,0.000000,0.000000,0.000000,1.000000
HDL_low,9232.0,0.249783,0.432911,0.000000,0.000000,0.000000,0.000000,1.000000
High_BP,9232.0,0.522747,0.499509,0.000000,0.000000,1.000000,1.000000,1.000000
Abnormal_glucose,9232.0,0.350953,0.477294,0.000000,0.000000,0.000000,1.000000,1.000000
metabolic_syndrome,9232.0,0.270039,0.444004,0.000000,0.000000,0.000000,1.000000,1.000000

In [10]:
missing_values = data.isnull().sum()
print(missing_values.sort_values(ascending=True))

Unnamed: 0                           0
High_BP                              0
HDL_low                              0
Triglycerides_high                   0
Abdominal_obesity                    0
Abnormal_glucose                     0
diabetes_question                    0
chol_question                        0
bp_question                          0
health_insurance                     0
marital_status                       0
metabolic_syndrome                   0
id                                   0
race                                 0
persWt                               0
age                                  0
examWt                               0
gender                               0
psu                                  0
strata                               0
education                            0
food_security                      689
weight                             830
height                             837
monthly_poverty_level_category     849
bmi                                851
urine_alb_creat                    913
hba1c                             1151
waist_circumference               1177
total_cholesterol                 1311
hdl_cholesterol                   1311
hscrp                             1368
systolicBP1                       1584
diastolicBP1                      1584
systolicBP2                       1595
diastolicBP2                      1595
systolicBP3                       1613
diastolicBP3                      1613
monthly_poverty_level_index       2059
fasting.glucose                   5228
triglycerides                     5298
bp_medication                     5962
chol_medication                   6490
antidiabetic_pills                6636
pregnancy_status                  7358
take_insulin                      7812
dtype: int64

In [11]:
data.shape

(9232, 46)

In [12]:
#Exclude pregnant patients
data = data[data['pregnancy_status'] != 1]

In [13]:
data.shape

(9145, 46)

In [14]:
# Drop the column we dont want:
df = data.drop(columns=['pregnancy_status'], axis=1)

In [15]:
# Drop the first unnamed column
df.drop(columns=df.columns[df.columns.str.contains('Unnamed')][0], inplace=True)

In [16]:
df.shape

(9145, 44)

In [17]:
# Save DataFrame as CSV
df.to_csv('merged_with_target.csv', index=False)